# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target ‘AVStream’ do
 	pod 'CNMLib'
#    pod 'GPUImage', '~> 0.1.7'
pod 'FMDB'
pod 'Masonry'
pod 'MJRefresh'
end
